name: "turbo_cache_server_otel"

services:
  s3_bucket:
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_CONSOLE_ENABLE: "true"
    volumes:
      - s3_data:/data
      - s3_logs:/logs
    command:
      - --address
      - :9000
      - --console-enable
      - --access-key
      - rustfsadmin
      - --secret-key
      - rustfsadmin
      - /data

  # Observability
  collector:
    image: otel/opentelemetry-collector:0.153.0@sha256:6ed874ea083d67a3085acfc75343f2ad11d9abe6006d7ea4a16e2dba9af14e49
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317" # OTELP GRPC
      - "4318:4318" # OTELP HTTP

  prometheus:
    image: prom/prometheus:v3.11.3@sha256:e4254400b85610324913f0dc4acf92603d9984e7519414c5a12811aa6146acc3
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-otlp-receiver
    ports:
      - "9090:9090"

  jaeger:
    image: jaegertracing/jaeger:2.18.0@sha256:d2cbd047e44b50c11454820f84fd5f34c24a435e5301cf94fe026bf055db80b3
    ports:
      - "4317" # OTELP GRPC
      - "4318" # OTELP HTTP
      - "16686:16686" # Jaeger UI

volumes:
  s3_data:
  s3_logs:
  
